articles/urls.py
from django.urls import path, include
from .views import FilmView, full_list, main_page, play, registration, auth, profile, log_out, menu_choice, detail_upgrade, play_dice, play_cards, test, my_bets
from django.views.generic.base import RedirectView

app_name = 'articles'

urlpatterns = [
    path('api/', FilmView.as_view()),
    path('home/', main_page, name='home'),
    path('', RedirectView.as_view(url='home/')),
    path('articles/<int:article_id>/', detail_upgrade, name="show-article"),
    path('articles/', full_list, name='articles'),
    path('playing/', play, name="playing"),
    path('reg/', registration, name='reg'),
    path('auth/', auth, name='auth'),
    path('profile/<slug:slug>/', profile, name='profile'),
    path('logout/', log_out, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('menu/', menu_choice, name='menu'),
    path('playing/dice/', play_dice, name='dice'),
    path('playing/cards/', play_cards, name='cards'),
    path('test1/', test),
    path('bets/', my_bets, name='bets')
]

articles/templates/play/cards.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{% block content %}
{% if message %}
    <img src="{{card_image}}">
    <p style="color: white;">{{card}}</p>
    <p style="color: white;">{{message}}</p>
    <p style="color: white;">{{balance}}</p>
{% else %}
    <form method="post">
        {% csrf_token %}
        {{ form_card }}
        <button class="btn btn-secondary">Сделать ставку</button>
    </form>
{% endif %}
{% endblock %}
</body>
</html>

articles/templates/play/dice.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% if msg %}
    <p>{{user_name}}</p>
    <p>{{balance}}</p>
    <p>{{number}}</p>
    <p>{{msg}}</p>
{% else %}
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-primary">Сделать ставку</button>
    </form>
{% endif %}
{% endblock %}
</body>
</html>

articles/templates/play/playing.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title></title>
</head>
{% block content %}
<body class="playing">
<a href="{% url 'articles:dice' %}" class="btn btn-success">Play dice</a>
<a href="{% url 'articles:cards' %}" class="btn btn-success">Play cards</a>
{% endblock %}
</body>
</html>