articles/urls.py
from django.urls import path, include
from .views import FilmView, full_list, main_page, play, registration, auth, profile, log_out, menu_choice, detail_upgrade, play_dice, play_cards, test, my_bets
from django.views.generic.base import RedirectView

app_name = 'articles'

urlpatterns = [
    path('api/', FilmView.as_view()),
    path('home/', main_page, name='home'),
    path('', RedirectView.as_view(url='home/')),
    path('articles/<int:article_id>/', detail_upgrade, name="show-article"),
    path('articles/', full_list, name='articles'),
    path('playing/', play, name="playing"),
    path('reg/', registration, name='reg'),
    path('auth/', auth, name='auth'),
    path('profile/<slug:slug>/', profile, name='profile'),
    path('logout/', log_out, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('menu/', menu_choice, name='menu'),
    path('playing/dice/', play_dice, name='dice'),
    path('playing/cards/', play_cards, name='cards'),
    path('test1/', test),
    path('bets/', my_bets, name='bets')
]

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'bootstrap/css/static/favicon.svg' %}">
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
    <meta charset="UTF-8">
    <script>
     $(document).ready(function(){
        $('.dropdown-toggle').dropdown()
    });
</script>
    <title>{{ title }}</title>
</head>
<body>
<header class="p-3 bg-dark text-white border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'articles:home' %}" class="nav-link px-2 text-warning">Home</a></li>
            <li><a href="{% url 'articles:articles' %}" class="nav-link px-2 text-white">Articles</a></li>
            <li><a href="{% url 'articles:bets' %}" class="nav-link px-2 text-white">Bets</a></li>
            <li><a href="{% url 'articles:menu' %}" class="nav-link px-2 text-white">Menu</a></li>
            <li><a href="{% url 'articles:playing' %}" class="nav-link px-2 text-white">Playing</a></li>
            <li><a href="http://t.me/lizadegu_bot" class="nav-link px-2 text-white">Chat with my bot</a></li>
        </ul>
        <div class="text-end">
            {% if user.is_authenticated %}
            <p>hello, {{user.username}}</p>
            <div class="dropdown text-end">
            <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="true">
                <img src="{{user.profile.pic}}" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" href="{% url 'articles:profile' user.profile.slug%}">Go to profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'articles:logout' %}">Sign out</a></li>
          </ul>
        </div>
            {% else %}
            <a class="btn btn-outline-light me-2" href="{% url 'articles:auth' %}">Login</a>
            <a class="btn btn-warning" href="{% url 'articles:reg' %}">Sign-up</a>
            {% endif %}
        </div>
      </div>
    </div>
  </header>
<main>
{% block content %}
{% endblock %}
</main>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-6 border-top bg-dark" style="padding: 20px;">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <img src="{% static 'bootstrap/css/static/favicon.svg' %}" width="30" height="30">
      </a>
      <span class="mb-3 mb-md-0 text-white">&copy; 2022 Company, Inc</span>
    </div>
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="https://t.me/dreamless21"><img src="{% static 'bootstrap/css/static/icons/twitter.svg' %}" width="30" height="30"></a></li>
      <li class="ms-3"><a class="text-muted" href="https://t.me/dreamless21"><img src="{% static 'bootstrap/css/static/icons/facebook.svg' %}" width="30" height="30"></a></li>
      <li class="ms-3"><a class="text-muted" href="https://t.me/dreamless21"><img src="{% static 'bootstrap/css/static/icons/instagram.svg' %}" width="30" height="30"></a></li>
    </ul>
  </footer>
</body>
</html>

articles/templates/articles/bets.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<table class="table table-striped table-dark">
  <thead>
    <tr>
        <th scope="col">Айди матча</th>
        <th scope="col">Название матча</th>
        <th scope="col">Ставка</th>
        <th scope="col">Сумма ставки</th>
        <th scope="col">Коэффициент</th>
        <th scope="col">Дата</th>
        <th scope="col">Результат</th>
        <th scope="col">Сумма выигрыша</th>
    </tr>
  </thead>
    <tbody>
{% for bet in bets %}
<tr>
    <th scope="row">{{bet.id}}</th>
    <td>{{bet.match_name}}</td>
    <td>{{bet.bet}}</td>
    <td>{{bet.amount}}</td>
    <td>{{bet.koef}}</td>
    <td>{{bet.dt}}</td>
    {% if bet.result == 'Победа' %}
    <td style="color: green;">{{bet.result}}</td>
    {% elif bet.result == 'Проигрыш' %}
    <td style="color: red;">{{bet.result}}</td>
    {% else %}
    <td style="color: yellow;">{{bet.result}}</td>
    {% endif %}
    <td>{{bet.total_win}}</td>
</tr>
{% endfor %}
    </tbody>
</table>
{% endblock %}
</body>
</html>

articles/templates/articles/food.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <title>{{Title}}</title>
</head>
<body>
{% block content %}
<div class="container" style="margin: 20px;">
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
    {{ field }}
    <br>
    {% endfor %}

    <button class="btn btn-primary">OK</button>
    </form>
</div>

{% endblock %}
</body>
</html>

articles/templates/articles/full_list.html
<!DOCTYPE html>
<html class="full" lang="en">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>List of films</title>
</head>
{% block content %}
<body>
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-white">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>
  <div class="album py-5 bg-dark">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% if film_list %}
          {% for film in film_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static film.pic %}">
            <div class="card-body">
              <p class="card-text">{{film.description|truncatechars:200}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" class="btn btn-sm btn-outline-secondary" href="{{ film.id }}">Подробнее</a>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">Рейтинг: {{ film.rating }}</small>
              </div>
            </div>
          </div>
        </div>
          {% endfor %}
          {% else %}
          <p>No film are available.</p>
          {% endif %}
      </div>
    </div>
  </div>
</main>
</body>
{% endblock %}

</html>

articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
<body>
<div class="bg-image index">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <main class="px-3">
    <h1>Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-dark">Learn more</a>
    </p>
  </main>
</div>
    {% endblock %}
</div>
</body>
</html>

articles/templates/articles/new_detail.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% extends 'articles/base.html' %}
		{% load static %}
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		<title>main page</title>
		<!-- Loading third party fonts -->
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="fonts/novecento-font/novecento-font.css" rel="stylesheet" >
		<!-- Loading main css file -->
		<!--link rel="stylesheet"  href="{% static 'bootstrap/css/style_tmp.css' %}"-->
		<!--[if lt IE 9]>
		<![endif]-->
	    <meta charset="UTF-8">
	</head>

	{% block content %}
	<body  style="color: #888;">
		<div id="site-content">
			<main class="main-content">
				<div class="hero">
					<div class="container">
						<div class="row">
							<div class="col-md-8">
								<figure><img src="{% static article.pic %}" alt=""></figure>
							</div>
							<div class="col-md-4">
								<div class="hero-content">
									<h1 class="hero-title">{{article.name}}</h1>
									<h2>Год выпуска</h2>
									<p>{{article.year}}</p>
									<h2>Рейтинг</h2>
									<p>{{article.rating}}</p>
									<form method="post">
        								{% csrf_token %}
        								{% if not in_fav %}
										<button name="favorite" value="add" class="button">Add to favorite</button>
        								{% else %}
            							<button name="favorite" value="delete" class="button">Delete from favorite</button>
										{% endif %}
    								</form>
								</div>
							</div>
						</div>
					</div>
				</div> <!-- .hero-slider -->
				
				<div class="fullwidth-block" data-bg-color="#111113">
					<div class="container">
						<div class="row">
							<div class="col-md-8">
								<h2>Описание</h2>
								<p>{{article.description}}</p>
							</div>
							<div class="col-md-4">
								<div class="latest-news">
									<h3>Latest News</h3>
									<ul>
										<li>
											<h3 class="entry-title"><a href="#">Enim ad minim veniam quis nostrud</a></h3>
											<small class="date">07/04/2014</small>
										</li>
										<li>
											<h3 class="entry-title"><a href="#">Duis aute irure dolor in reprehenderit</a></h3>
											<small class="date">07/04/2014</small>
										</li>
									</ul>
								</div> <!-- .latest-news -->
							</div>
						</div> <!-- .row -->
					</div> <!-- .container -->
				</div> <!-- .fullwidth-block -->
				<!--Сделать рецензии-->
				<div class="fullwidth-block">
					<div class="container">
						<div class="row feature-list-section">
							<div class="col-md-4">
								<div class="feature">
									<header>
										<img src="images/icon-1.png" class="feature-icon">
										<div class="feature-title-copy">
											<h2 class="feature-title">Criminal Things</h2>
											<small class="feature-subtitle">Lorem ipsum dolor sit</small>
										</div>
									</header>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias doloremque, quis, eaque minus harum modi eius veritatis consequuntur expedita impedit ad, facilis. Asperiores assumenda aperiam atque, accusamus cupiditate vero sit!</p>
									<a href="#" class="more-link">Read More</a>
								</div>
							</div>
							<div class="col-md-4">
								<div class="feature">
									<header>
										<img src="images/icon-2.png" class="feature-icon">
										<div class="feature-title-copy">
											<h2 class="feature-title">Estate Planning</h2>
											<small class="feature-subtitle">Lorem ipsum dolor sit</small>
										</div>
									</header>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias doloremque, quis, eaque minus harum modi eius veritatis consequuntur expedita impedit ad, facilis. Asperiores assumenda aperiam atque, accusamus cupiditate vero sit!</p>
									<a href="#" class="more-link">Read More</a>
								</div>
							</div>
							<div class="col-md-4">
								<div class="feature">
									<header>
										<img src="images/icon-3.png" class="feature-icon">
										<div class="feature-title-copy">
											<h2 class="feature-title">Employment Law</h2>
											<small class="feature-subtitle">Lorem ipsum dolor sit</small>
										</div>
									</header>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias doloremque, quis, eaque minus harum modi eius veritatis consequuntur expedita impedit ad, facilis. Asperiores assumenda aperiam atque, accusamus cupiditate vero sit!</p>
									<a href="#" class="more-link">Read More</a>
								</div>
							</div>
						</div>


					</div>
				</div>

			</main> <!-- .main-content -->
	<section style="background-color: #161719;">
    <form method="POST">
    {% csrf_token %}
        <div class="form-control form-control-lg" style="width: 70%; height: 250px; padding: 10px; margin: auto;">
            {{ form }}
            <button class="btn btn-outline-success">Send</button>
        </div>
    </form>
    {% if comments %}
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">

      <div class="col-md-12 col-lg-10 text-white">
          <div class="card-body p-4">
        <h4 class="mb-0">Recent comments</h4>
            <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>
              </div>
        <div class="card text-dark">
            {% for com in comments %}
          <div class="card-body p-4">
            <div class="d-flex flex-start">
              <img class="rounded-circle shadow-1-strong me-3"
                src="{{com.author.pic}}" alt="avatar" width="60"
                height="60" />
              <div>
                  <h6 class="fw-bold mb-1"><a href="{% url 'articles:profile' com.author.slug %}" style="text-decoration: none; color: black;">{{com.author_name}}</a></h6>
                <div class="d-flex align-items-center mb-3">
                  <p class="mb-0">
                    {{com.dt_published}}
                    <span class="badge bg-success">OK</span>
                  </p>
                </div>
                <p class="mb-0">
                    {{com.comment_text}}
                </p>
              </div>
            </div>
          {% if user.id == com.author_id %}
              <form method="post">
                  {% csrf_token %}
                  <button class="btn btn-danger" name="delete-button" value="{{com.id}}">Delete this message</button>
              </form>

          {% endif %}
          </div>
          <hr class="my-0" />
            {% endfor %}
        </div>
      </div>
    </div>
  </div>
    {% else %}
    <p>Комментариев нет, вы можете оставить первый!</p>
    {% endif %}
	</section>


		</div> <!-- #site-content -->
	{% endblock %}
		

		<script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		
	</body>

</html>

articles/templates/articles/old_detail.html

<!DOCTYPE html>
<html lang="en" class="detail">
<head>
    {% extends 'articles/base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<main>
    {% block content %}
    <div class="text-bg-dark p-3">
    <p>{{ article.name }}</p>
    <p>{{ article.year }}</p>
    <p>{{ article.rating }}</p>
    <img src="{% static article.pic %}" class="rounded">
    <p>{{ article.description }}</p>
</div>
    <div>

    <form method="post">
        {% csrf_token %}
        {% if not in_fav %}
        <div style="margin: 30px;">
            <button name="favorite" value="add" class="btn btn-danger">Add to favorite</button>
        </div>
        {% else %}
        <div style="margin: 30px">
            <button name="favorite" value="delete" class="btn btn-danger">Delete from favorite</button>
        </div>

        {% endif %}
    </form>


</div>

<section style="background-color: gray">
    <form method="POST">
    {% csrf_token %}
        <div class="form-control form-control-lg" style="width: 70%; height: 250px; padding: 10px; margin: auto;">
            {{ form }}
            <button class="btn btn-outline-success">Send</button>
        </div>
    </form>
    {% if comments %}
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">

      <div class="col-md-12 col-lg-10 text-white">
          <div class="card-body p-4">
        <h4 class="mb-0">Recent comments</h4>
            <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>
              </div>
        <div class="card text-dark">
            {% for com in comments %}
          <div class="card-body p-4">
            <div class="d-flex flex-start">
              <img class="rounded-circle shadow-1-strong me-3"
                src="{{com.author.pic}}" alt="avatar" width="60"
                height="60" />
              <div>
                  <h6 class="fw-bold mb-1"><a href="{% url 'articles:profile' com.author_name %}" style="text-decoration: none; color: black;">{{com.author_name}}</a></h6>
                <div class="d-flex align-items-center mb-3">
                  <p class="mb-0">
                    {{com.dt_published}}
                    <span class="badge bg-success">OK</span>
                  </p>
                </div>
                <p class="mb-0">
                    {{com.comment_text}}
                </p>
              </div>
            </div>
          {% if user.id == com.author_id %}
              <form method="post">
                  {% csrf_token %}
                  <button class="btn btn-danger" name="delete-button" value="{{com.id}}">Delete this message</button>
              </form>

          {% endif %}
          </div>
          <hr class="my-0" />
            {% endfor %}
        </div>
      </div>
    </div>
  </div>
    {% else %}
    <p>Комментариев нет, вы можете оставить первый!</p>
    {% endif %}
</section>




{% endblock %}
</main>
</body>
</html>

articles/templates/articles/searching_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>searched</title>
</head>
<body>
{% if matched %}
    {% for film in matched %}
    <p><a href="{{ film.id }}">{{ film.name }}</a></p>
    {% endfor %}
{% else %}
    <p>Совпадений не найдено</p>
{% endif %}
</body>
</html>

articles/templates/articles/test_bootstrap.html
<!DOCTYPE html>
<html>
  <head>
    <title>Business Theme</title>
    <style type="text/css">
      * {
        margin: 0;
        padding: 0;
      }
      body {
        font-family: sans-serif;
      }
      header {
        height: 88px;
        border-bottom: 1px solid #828282;
        width: 100%;
        margin: 0 auto;
      }

      nav {
        text-align: center;
      }

      .link {
        display: inline-block;
        margin-top: 33px;
        margin-right: 125px;
        font-weight: 600;
        color: #828282;
        text-decoration: none;
      }
      .link:hover {
        color: #000;
      }
      .wrapper {
        width: 943px;
        margin-top: 40px;

      }
      .man_nick {
        margin-left: 200px;
        font-size: 47px;
        font-weight: bold;
      }
      .data_text {
        margin-left: 682px;
      }
      .this_text {
        display: inline-block;
        height: 143px;
      }
      .data_text {
        margin-bottom: 50px;
      }
    </style>
  </head>
  <body>
    <header>
      <nav>
        <a href="", class="link">Home</a>
        <a href="", class="link">About Me</a>
        <a href="", class="link">Skills</a>
        <a href="", class="link">Portfolio</a>
        <a href="", class="link">Contacts</a>
      </nav>
    </header>
    <section class="wrapper">
      <div class="this_text">
        <p class="man_nick">Denis <br />
        Novik</p>
        <p class="data_text">UX|UI Designer <br />
        24 years old, Minsk</p>
      </div>
    </section>
  </body>
</html>